DiplomaProject-master/WebAPI/Controllers/DestinationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Business.Interfaces;
using WebAPI.Authorization;
using WebAPI.Helpers;
using Business.JSONModels;
using DataLayer.Models;
namespace WebAPI.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class DestinationController : ControllerBase
    {
        private readonly IDestinationService _destinationService;

        public DestinationController(IDestinationService destinationService)
        {
            _destinationService = destinationService;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var destinations = await _destinationService.GetAll();
            return Ok(destinations);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var destinations = await _destinationService.GetById(id);
            return Ok(destinations);
        }

        [Authorize(Role.Admin, Role.Moderator)]
        [HttpPost("[action]")]
        public async ValueTask<IActionResult> Create(DestinationModel model)
        {
            await _destinationService.CreateAsync(model);
            DestinationModel destination = await _destinationService.GetByAsync(d=> d.Name==model.Name);
            return CreatedAtAction("create", destination); 
        }

        [Authorize(Role.Admin, Role.Moderator)]
        [HttpPatch("[action]")]
        public async ValueTask<IActionResult> Edit(DestinationModel model)
        {
                await _destinationService.EditAsync(model);
                DestinationModel destination = await _destinationService.GetById(model.Id);
                return CreatedAtAction("create", destination);
           
        }

        [Authorize(Role.Admin, Role.Moderator)]
        [HttpDelete("[action]")]
        public async Task<IActionResult> Delete(DestinationModel model)
        {
            await _destinationService.DeleteAsync(model.Id);
            return Ok(new JSONMessage("Post deleted successfully!"));
        }
    }
}

DiplomaProject-master/WebAPI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticalAsignment.Web</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PracticalAsignment.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Destination" asp-action="GetAll">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PracticalAsignment.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>